version: '3.7'

services:
  web:
    build: .
    # command: python /code/manage.py runserver 0.0.0.0:8000
    command: gunicorn store_improved.wsgi -b 0.0.0.0:8000
    environment:
      - ENVIRONMENT=development
      - SECRET_KEY=djypfnjxzl+9eft_8xze&jf-@rnlw&*+ly0c3c)$qe*l-gszff
      - DEBUG=1
      - STRIPE_TEST_PUBLISHABLE_KEY=pk_test_YNrQXKztTVJfRxfyhNyUQ39t003ukXlb3k
      - STRIPE_TEST_SECRET_KEY=sk_test_9dmMPhY4vAl5Ty3BscXOimn900HVbkQXXG
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
