# Generated by Django 3.0.4 on 2020-05-23 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_order_orderline'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_address1',
            field=models.CharField(default='n', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address2',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_city',
            field=models.CharField(default='n', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='billing_country',
            field=models.CharField(default='n', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='billing_name',
            field=models.CharField(default='n', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='billing_zip_code',
            field=models.CharField(default='n', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address1',
            field=models.CharField(default='n', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address2',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(default='n', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_country',
            field=models.CharField(default='n', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_name',
            field=models.CharField(default='n', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_zip_code',
            field=models.CharField(default='n', max_length=12),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AddressUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('address1', models.CharField(max_length=60, verbose_name='Address line 1')),
                ('address2', models.CharField(blank=True, max_length=60, verbose_name='Address line 2')),
                ('zip_code', models.CharField(max_length=12, verbose_name='ZIP / Postal code')),
                ('city', models.CharField(max_length=60)),
                ('country', models.CharField(choices=[('uk', 'United Kingdom'), ('us', 'United States of America')], max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
