# Generated by Django 3.0.4 on 2020-05-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200523_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_address1',
            field=models.CharField(default='None', max_length=60),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_address2',
            field=models.CharField(blank=True, default='None', max_length=60),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_city',
            field=models.CharField(default='None', max_length=60),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_country',
            field=models.CharField(default='N', max_length=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_name',
            field=models.CharField(default='None', max_length=60),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_zip_code',
            field=models.CharField(default='None', max_length=12),
        ),
    ]
